spring.application.name=hello-spring-api

market.symbols=BTC-USD,ETH-USD
market.intervals=1s,5s,1m,15m,1h
market.simulator-enabled=true
market.simulator-fixed-rate-ms=100
market.simulator-min-ticks-per-run=1
market.simulator-max-ticks-per-run=12

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.datasource.hikari.maximum-pool-size=10

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
